[project]
name = "llmplus"
version = "0.0.7dev"
description = "A python package for developing AI applications with local LLMs."
authors = [
    {name = "Pok Hin Tam", email = "nathan1295@gmail.com"},
]
dependencies = [
    "torch",
    "torchvision",
    "torchaudio",
    "llama-cpp-python[server]",
    "click",
    "transformers>=4.35.0",
    "accelerate>=0.25.0",
    "sentence-transformers",
    "langchain",
    "faiss-cpu",
    "optimum",
    "gradio>=4.0",
    "duckduckgo-search",
    "fake-useragent",
    "openai>=1.0.0",
    "tiktoken",
    "protobuf",
    "beautifulsoup4",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
llmplus = "llmplus.cli:cli"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
package-type = "library"
src-layout = true

