[project]
name = "llmplus"
description = "A python package for developing AI applications with local LLMs."
dynamic = ["version"]
authors = [
    {name = "Pok Hin Tam", email = "nathan1295@gmail.com"},
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "torch>=2.1.0",
    "llama-cpp-python[server]",
    "click",
    "transformers>=4.35.0",
    "accelerate>=0.25.0",
    "sentence-transformers",
    "langchain",
    "faiss-cpu",
    "optimum",
    "gradio>=4.2",
    "duckduckgo-search",
    "fake-useragent",
    "openai>=1.0.0",
    "tiktoken",
    "protobuf",
    "beautifulsoup4",
]

[project.scripts]
llmplus = "llmplus.cli:cli"

[project.optional-dependencies]
cpu = [
    "torch@https://download.pytorch.org/whl/cpu"
]
mac = [
    "torch>=2.1.0"
] 
cu121 = [
    "torch@https://download.pytorch.org/whl/cu121",
    "auto-gptq>=0.6.0",
    "autoawq"
]
cu118 = [
    "torch@https://download.pytorch.org/whl/cu118",
    "auto-gptq@https://huggingface.github.io/autogptq-index/whl/cu118",
    "autoawq"
]

[[tool.pdm.source]]
url = "https://huggingface.github.io/autogptq-index/whl/cu118"
verify_ssl = true
name = "gptqcu118"

[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cpu"
verify_ssl = true
name = "torchcpu"

[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cu118"
verify_ssl = true
name = "torchcu118"

[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cu121"
verify_ssl = true
name = "torchcu121"

[build-system]
requires = ["pdm-backend", "pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pdm]
package-type = "library"
src-layout = true

